version: '3.7'
services:
  ########################################################
  #### Provide build instructions for all i40-aas images
  ##########################################
  i40-aas-data-manager:
    image: sapi40/i40-aas-data-manager-type2:${BUILD_TAG}
    build:
      context: src/java
      dockerfile: ../docker/data-manager/Dockerfile
