version: '3.7'
services:
  ########################################################
  i40-aas-data-manager:
    image: sapi40/i40-aas-data-manager
    ports:
      - "${CORE_DATA_MANAGER_PORT}:${CORE_DATA_MANAGER_PORT}"
    environment:
      ## logging
      - LOGGING_LOGLEVEL=${LOGGING_LOGLEVEL}
      - LOGGING_LOGOUTPUT=${LOGGING_LOGOUTPUT}
      ## adapter-registry
      - CORE_REGISTRIES_ADAPTERS_HOST=i40-aas-adapter-registry
      - CORE_REGISTRIES_ADAPTERS_PORT=${CORE_REGISTRIES_ADAPTERS_PORT}
      - CORE_REGISTRIES_ADAPTERS_URL_SUFFIX=${CORE_REGISTRIES_ADAPTERS_URL_SUFFIX}
      - CORE_REGISTRIES_ADAPTERS_USER=${CORE_REGISTRIES_ADAPTERS_USER}
      - CORE_REGISTRIES_ADAPTERS_PASSWORD=${CORE_REGISTRIES_ADAPTERS_PASSWORD}
      ## data-manager
      - CORE_DATA_MANAGER_PORT=${CORE_DATA_MANAGER_PORT}
      - CORE_DATA_MANAGER_USER=${CORE_DATA_MANAGER_USER}
      - CORE_DATA_MANAGER_PASSWORD=${CORE_DATA_MANAGER_PASSWORD}
      ## TLS
      - TLS_ENABLED=${TLS_ENABLED}
      - TLS_KEYFILE=${TLS_KEYFILE}
      - TLS_CERTFILE=${TLS_CERTFILE}
    volumes:
      - ./src/compose/volumes/certs/:/etc/ssl/certs/

  ########################################################
  #### third party containers
  ##########################################

  postgres:
    image: postgres:alpine
    ports:
      - "${CORE_REGISTRIES_ENDPOINTS_DATABASE_PORT}:${CORE_REGISTRIES_ENDPOINTS_DATABASE_PORT}"
    volumes:
      - ./src/compose/volumes/postgres/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${CORE_REGISTRIES_ENDPOINTS_DATABASE_USER}
      - POSTGRES_PASSWORD=${CORE_REGISTRIES_ENDPOINTS_DATABASE_PASSWORD}
      - POSTGRES_MULTIPLE_DATABASES="${CORE_REGISTRIES_ENDPOINTS_DATABASE_NAME}","${CORE_REGISTRIES_ADAPTERS_DATABASE_NAME}"
  ##########################################
